-- Таблица procedures необходима для JApi бэка для разрешения вызова хранимых процедур
-- хранимые процедуры
CREATE TABLE "config"."procedures" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "name" varchar NOT NULL,
    "connect" varchar NOT NULL,
    "id_right" varchar NULL,
    "result_array" boolean DEFAULT true,
    "call" varchar NOT NULL
);

CREATE UNIQUE INDEX procedures_name_unique ON config."procedures" ("name");

COMMENT ON TABLE "config"."procedures" IS 'Таблица для вызова хранимых процедур в бд';

COMMENT ON COLUMN config.procedures.id IS 'Первичный ключ';

COMMENT ON COLUMN config.procedures."name" IS 'Имя хранимой процедуры';

COMMENT ON COLUMN config.procedures."connect" IS 'Имя соединения к бд';

COMMENT ON COLUMN config.procedures."call" IS 'Sql код вызова хранимой процедуры';

COMMENT ON COLUMN config.procedures."result_array" IS 'Возвращается ли массив или объект';

COMMENT ON COLUMN config.procedures.id_right IS 'Внешний ключ право необходимое для вызова процедуры';

-- Дочерняя таблица procedures_parameters для таблицы procedures
-- параметры хранимых процедур
CREATE TABLE "config"."procedures_parameters" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "name" varchar NOT NULL,
    "type" int NOT NULL,
    "type_parameters" varchar NOT NULL,
    "index" int NOT NULL,
    "id_procedures" int NOT NULL,
    -- у процедуры не могут быть одинаковые имена у входящих параметров
    UNIQUE ("name", "id_procedures"),
    -- у процедуры не могут быть index с одинаковыми значениями
    UNIQUE ("index", "id_procedures"),
    CONSTRAINT procedures_in_fk1 FOREIGN KEY (id_procedures) REFERENCES config."procedures"(id)
);

COMMENT ON TABLE "config"."procedures_parameters" IS 'Таблица для указания входящих параметров в хранимые процедуры';

COMMENT ON COLUMN config.procedures_parameters.id IS 'Первичный ключ';

COMMENT ON COLUMN config.procedures_parameters."name" IS 'Имя параметра';

COMMENT ON COLUMN config.procedures_parameters."type" IS 'Тип параметра (значение)';

COMMENT ON COLUMN config.procedures_parameters."type_parameters" IS 'Тип параметра (хранимой процедуры: in, out)';

COMMENT ON COLUMN config.procedures_parameters."index" IS 'Индекс параметра';

COMMENT ON COLUMN config.procedures_parameters."id_procedures" IS 'Внешний ключ процедуры';